### ISSUE TITLE
root password?

### ISSUE THREAD

**Issue by Kikobeats** [ffuenf/vagrant-boxes#15]
Hello man. I'm trying to set up your box with vagrant but, when is installing Guest additions request me put the root password. What is it?

![](http://i.imgur.com/k9HDORb.png)

**Comment by arosenhagen** [comment]
This has nothing to do with the GuestAdditions. Administrator privileges of your host system are needed when mounting NFS shares (you have setup shared folders in your Vagrantfile and therefore vagrant needs Administrator privileges). So this is the user password on your host.
