### ISSUE TITLE
Inability to download or update vmware boxes from Atlas

### ISSUE THREAD

**Issue by harrisony** [ffuenf/vagrant-boxes#18]
hiya,
I noticed when trying to update my the ubuntu-14.10-server-amd64 box although it also happens with downloading new boxes. 

On Atlas, your newer boxes have "vmware" as their provider while Vagrant is actually looking for "vmware_desktop". 

Keep up the good work :smile:

**Comment by arosenhagen** [comment]
should be fixed now. naming between packer / vagrant / atlas for vmware is still a mess in my eyes :-/
