### ISSUE TITLE
Build box is broken because of VMWare tools

### ISSUE THREAD

**Issue by Annakan** [ffuenf/vagrant-boxes#20]
It seems the released binary box is broken because somebody did a "apt-get upgrade" that updated the kernel  without rebuilding the vmware tools nor setting their "auto rebuild" to true...

Now the box is stuck with the " Waiting for HGFS kernel module to load... " and one need to `vagrant ssh` in it and do a `echo "answer AUTO_KMODS_ENABLED yes" | sudo tee -a /etc/vmware-tools/locations` before a `vagrant reload`

Would it be possible to rebuild the box "in sync" with the vmware tools and add something like this to the 
builder
```
# Ensure that VMWare Tools recompiles kernel modules when we update the linux images
$fix_vmware_tools_script = <<SCRIPT
sed -i.bak 's/answer AUTO_KMODS_ENABLED_ANSWER no/answer AUTO_KMODS_ENABLED_ANSWER yes/g' /etc/vmware-tools/locations
sed -i.bak 's/answer AUTO_KMODS_ENABLED no/answer AUTO_KMODS_ENABLED yes/g' /etc/vmware-tools/locations
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # ...
  config.vm.provision :shell, :inline => $fix_vmware_tools_script
end
```
or 
 `echo "answer AUTO_KMODS_ENABLED yes" | sudo tee -a /etc/vmware-tools/locations` 

For the full explanation Cf. : https://dantehranian.wordpress.com/2014/08/19/vagrant-vmware-resolving-waiting-for-hgfs-kernel-module-timeouts/  and https://github.com/mitchellh/vagrant/issues/4362

**Comment by arosenhagen** [comment]
in v1.0.13 I switched to open-vm-tools as recommended by VMware. Can you check, if this solves your problem? Moreover I think this is more a configuration in vagrant than in packer.

**Comment by Annakan** [comment]
Hello sorry for the delay in answering.
I tried the new box and I am stuck at the same point, except than now the "force rebuilt trick" does not work anymore  since the open-vm-tools do not respond to the same configuration apparently.

To be more explicit, and after some digging I found the following quote 
> Linux kernel versions 3.10 and later include all of the Linux drivers present in open-vm-tools except the vmhgfs driver. The vmhgfs driver is required for enabling shared folders feature.
(from https://github.com/vmware/open-vm-tools)

So it seems the HGFS kernel module is not loaded or loadable.. and indeed, in the VM this is shown : 

    vagrant@vagrant:~$ cat /proc/modules | grep 'vm'
    vmw_balloon 16384 0 - Live 0x0000000000000000
    vmw_vmci 65536 0 - Live 0x0000000000000000
    vmwgfx 180224 1 - Live 0x0000000000000000
    ttm 98304 1 vmwgfx, Live 0x0000000000000000
    drm_kms_helper 131072 1 vmwgfx, Live 0x0000000000000000
    drm 348160 4 vmwgfx,ttm,drm_kms_helper, Live 0x0000000000000000

and : 

    vagrant@vagrant:~$ lsmod | grep -i hgfs
    vagrant@vagrant:~$

I can't figure why at the moment though.

The previous box/image with the official  `vmware-tools` worked fine **except** on first boot, what I suspect is that just having the box build with the echo `"answer AUTO_KMODS_ENABLED yes" >>  /etc/vmware-tools/locations` or at least with the tools recompiled in sync with the kernel would have done the trick.
